language: objective-c
osx_image: xcode11.0
cache:
  - bundler
  - cocoapods
xcode_workspace: FinalProject.xcworkspace
xcode_scheme: "FinalProject"
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install --repo-update
  - gem install linterbot
  - brew install swiftlint
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
before_script:
  - chmod a+x ./scripts/linter
script:
  - ./scripts/linter
